version: "3"

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    image: mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx
    env_file:
      - .env
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    image: wordpress
    env_file:
      - .env
    depends_on: 
      - mariadb
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    restart: always

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bluzi/data/mariadb
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bluzi/data/wordpress

networks:
  inception:
    name: inception
    driver: bridge
